#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CarMon.Resource", IsApplication=true)]

namespace CarMon
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int EntryType = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int ExpendatureList = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int InputNumber = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int Kilometers = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int NewEntry = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int costText = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int create = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int help = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int new_game1 = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int reset = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NewEntry = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int NewEntry = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int NewEntryKilometerText = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050005
			public const int GeneralButton = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int GeneralFont = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int ListFont = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int ThemeSelector = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int myTheme_ActionBar = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int myTheme_ActionBar_Text = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
